import eventimg from "../public/eventimg.png";

const eventCardItems = [
  {
    id: 1,
    title: "Lakeside Camping at Pawna",
    image: eventimg,
    date: "NOV 25 - 26",
    time: "8:30 AM - 7:30 PM",
    description: "Adventure Geek - Explore the Unexplore...",
    price: "IDR 400,000",
    interested: 14,
    category: "Adventure",
  },
  {
    id: 2,
    title: "Art Exhibition: Modern Perspectives",
    image: eventimg,
    date: "DEC 10 - 12",
    time: "10:00 AM - 6:00 PM",
    description: "Discover the latest trends in contemporary art...",
    price: "Free Admission",
    interested: 8,
    category: "Art",
  },
  {
    id: 3,
    title: "Tech Conference 2024",
    image: eventimg,
    date: "JAN 15 - 16",
    time: "9:00 AM - 5:00 PM",
    description: "Join industry leaders to explore the latest in technology...",
    price: "IDR 1,200,000",
    interested: 20,
    category: "Technology",
  },
  {
    id: 4,
    title: "Music Festival 2024",
    image: eventimg,
    date: "FEB 20 - 22",
    time: "3:00 PM - 11:00 PM",
    description: "Experience live performances from top artists...",
    price: "IDR 600,000",
    interested: 50,
    category: "Music",
  },
  {
    id: 5,
    title: "Startup Pitch Night",
    image: eventimg,
    date: "MAR 5",
    time: "6:00 PM - 9:00 PM",
    description: "Watch the best startups pitch their ideas...",
    price: "IDR 200,000",
    interested: 30,
    category: "Business",
  },
  {
    id: 6,
    title: "Yoga Retreat",
    image: eventimg,
    date: "APR 10 - 14",
    time: "7:00 AM - 5:00 PM",
    description: "Relax and rejuvenate with a five-day yoga retreat...",
    price: "IDR 2,500,000",
    interested: 25,
    category: "Health & Wellness",
  },
];

export default eventCardItems;
